package chatterbox;

import java.util.ArrayList;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import chatterbox.exception.ChatterBoxException;
import chatterbox.parser.Parser;
import chatterbox.storage.Storage;
import chatterbox.task.TaskList;
import chatterbox.ui.Ui;

public class ParserTest {
    @Test
    public void parseEmptyTodoDescription() {
        TaskList tasks = new TaskList(new ArrayList<>());
        Ui ui = new Ui();
        Storage storage = new Storage("./data/test.txt");
        assertThrows(ChatterBoxException.class, () -> { // generated by github copilot to get the assertion
            Parser.parse("todo ", tasks, ui, storage);
        });
    }

    @Test
    public void parse_invalidDeadline_exceptionThrown() {
        TaskList tasks = new TaskList(new ArrayList<>());
        Ui ui = new Ui();
        Storage storage = new Storage("./data/test.txt");

        assertThrows(ChatterBoxException.class, () -> {
            Parser.parse("deadline ", tasks, ui, storage);
        });
    }
}
