import java.util.ArrayList;
import java.util.Scanner;

public class ChatterBox {

    public static void main(String[] args) {
        String botName = "ChatterBox";
        boolean chatting = true;

        ArrayList<Task> tasks = new ArrayList<Task>();

        System.out.println("        Hello! I'm " + botName);
        System.out.println("        What can I do for you?");

        Scanner scanner = new Scanner(System.in);
        while (chatting) {
            try {
                if (scanner.hasNextLine()) { // Add this check
                    String userInput = scanner.nextLine();
                    if (userInput.equalsIgnoreCase("bye")) {
                        chatting = false;
                        break;

                    } else if (userInput.equalsIgnoreCase("list")) {
                        for (int i = 0; i < tasks.size(); i++) {
                            System.out.println("        " + (i + 1) + "." + tasks.get(i));
                        }

                    } else if (userInput.startsWith("mark")) {
                        String[] parts = userInput.split(" ");
                        int taskNumber = Integer.parseInt(parts[1]) - 1;// generated by github copilot to get the
                                                                        // taskNumber
                        Task index = tasks.get(taskNumber);
                        index.markAsDone();
                        System.out.println("        Nice! I've marked this task as done:");
                        System.out.println("          " + tasks.get(taskNumber).toString());

                    } else if (userInput.startsWith("unmark")) {
                        String[] parts = userInput.split(" ");
                        int taskNumber = Integer.parseInt(parts[1]) - 1; // generated by github copilot to get the
                                                                         // taskNumber
                        Task index = tasks.get(taskNumber);
                        index.markAsNotDone();
                        System.out.println("        OK, I've marked this task as not done yet:");
                        System.out.println("          " + tasks.get(taskNumber).toString());

                    } else if (userInput.startsWith("todo")) {
                        String task = userInput.substring(userInput.indexOf(" ") + 1); // generated by github copilot to
                                                                                       // get
                                                                                       // the
                                                                                       // task description
                        if (userInput.length() <= 4 || userInput.substring(5).trim().isEmpty()) { // generated by github
                                                                                                  // copilot to
                                                                                                  // check if
                                                                                                  // the
                                                                                                  // description
                                                                                                  // is empty
                            throw new ChatterBoxException("     OOPS!!! The description of a todo cannot be empty.");
                        }
                        ToDos newToDo = new ToDos(task);
                        tasks.add(newToDo);
                        System.out.println("        Got it. I've added this task:");
                        System.out.println("          " + newToDo.toString());
                        System.out.println("        Now you have " + tasks.size() + " tasks in the list.");
                    } else if (userInput.startsWith("deadline")) {
                        if (userInput.length() <= 8 || userInput.substring(9).trim().isEmpty()) {
                            throw new ChatterBoxException(
                                    "     OOPS!!! The description of a deadline cannot be empty.");
                        }
                        String[] parts = userInput.split("/by", 2);
                        String firstPart = parts[0].trim();
                        String task = firstPart.substring(firstPart.indexOf(" ") + 1);
                        // System.err.println(task);
                        String deadline = parts[1].trim();

                        Deadline newDeadline = new Deadline(task, deadline);
                        tasks.add(newDeadline);
                        System.out.println("        Got it. I've added this task:");
                        System.out.println("          " + newDeadline.toString());
                        System.out.println("        Now you have " + tasks.size() + " tasks in the list.");
                    } else if (userInput.startsWith("event")) {
                        if (userInput.length() <= 5 || userInput.substring(6).trim().isEmpty()) {
                            throw new ChatterBoxException("     OOPS!!! The description of an event cannot be empty.");
                        }
                        String[] parts = userInput.split("/to", 2); // generated by github copilot to get the task
                                                                    // description
                        String firstPart = parts[0].trim(); // generated by github copilot to get the task description
                        String taskAndAt = firstPart.substring(firstPart.indexOf(" ") + 1); // generated by github
                                                                                            // copilot
                                                                                            // to
                                                                                            // get the task description
                        String[] taskParts = taskAndAt.split("/from", 4); // generated by github copilot to get the task
                                                                          // description
                        String task = taskParts[0].trim(); // generated by github copilot to get the task description
                        String at = taskParts[1].trim(); // generated by github copilot to get the task description
                        String to = parts[1].trim(); // generated by github copilot to get the task description

                        Events newEvent = new Events(task, at, to);
                        tasks.add(newEvent);
                        System.out.println("        Got it. I've added this task:");
                        System.out.println("          " + newEvent.toString());
                        System.out.println("        Now you have " + tasks.size() + " tasks in the list.");
                    }

                    else {
                        Task newTask = new Task(userInput);
                        tasks.add(newTask);
                        System.out.println("        added: " + userInput);
                    }
                } else {
                    chatting = false;
                }
            } catch (ChatterBoxException e) {
                System.out.println(e.getMessage());
            }
        }
        System.out.println("        Bye. Hope to see you again soon!");
        scanner.close();
    }
}
