import java.util.ArrayList;

class Task {
    protected String description;
    protected boolean isDone;

    public Task(String description) {
        this.description = description;
        this.isDone = false;
    }

    public String getStatusIcon() {
        return (isDone ? "[X]" : "[ ]");
    }

    public void markAsDone() {
        this.isDone = true;
    }

    public void markAsNotDone() {
        this.isDone = false;
    }

    public String toString() {
        return getStatusIcon() + " " + description;
    }
}

public class ChatterBox {

    public static void main(String[] args) {
        String botName = "ChatterBox";
        boolean chatting = true;

        ArrayList<Task> tasks = new ArrayList<Task>();

        // Task t = new Task("read book");
        // Task t1 = new Task("return book");
        // Task t2 = new Task("buy bread");
        // t.markAsDone();

        System.out.println("        Hello! I'm " + botName);
        System.out.println("        What can I do for you?");

        while (chatting) {
            String userInput = System.console().readLine();
            if (userInput.equalsIgnoreCase("bye")) {
                chatting = false;
                break;
            } else if (userInput.equalsIgnoreCase("list")) {
                for (int i = 0; i < tasks.size(); i++) {
                    System.out.println("        " + (i + 1) + "." + tasks.get(i));
                }

            } else if (userInput.startsWith("mark")) {
                String[] parts = userInput.split(" ");
                int taskNumber = Integer.parseInt(parts[1]) - 1;// generated by github copilot to get the taskNumber
                Task index = tasks.get(taskNumber);
                index.markAsDone();
                System.out.println("        Nice! I've marked this task as done:");
                System.out.println("          " + tasks.get(taskNumber).toString());

            } else if (userInput.startsWith("unmark")) {
                String[] parts = userInput.split(" ");
                int taskNumber = Integer.parseInt(parts[1]) - 1; // generated by github copilot to get the taskNumber
                Task index = tasks.get(taskNumber);
                index.markAsNotDone();
                System.out.println("        OK, I've marked this task as not done yet:");
                System.out.println("          " + tasks.get(taskNumber).toString());

            } else {
                Task newTask = new Task(userInput);
                tasks.add(newTask);
                System.out.println("        added: " + userInput);
            }
        }
        System.out.println("        Bye. Hope to see you again soon!");
    }
}
