import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import java.io.BufferedWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.nio.file.Paths;
import java.time.LocalDate;
import java.time.LocalDateTime;

public class ChatterBox {
    static void saveTasks(Path path, ArrayList<Task> tasks) {
        try (BufferedWriter writer = Files.newBufferedWriter(
                path,
                StandardCharsets.UTF_8,
                StandardOpenOption.CREATE,
                StandardOpenOption.TRUNCATE_EXISTING)) {

            for (int i = 0; i < tasks.size(); i++) {
                writer.write(tasks.get(i).toFileString());
                writer.newLine();
            }
        } catch (Exception e) {
            System.out.println("Error saving tasks:");
            e.printStackTrace();
        }

    }

    public static void main(String[] args) {
        String botName = "ChatterBox";
        boolean isChatting = true;
        Scanner scanner = new Scanner(System.in);
        ArrayList<Task> tasks = new ArrayList<Task>();

        // Level-7: created the data file and check if it exists.
        Path txtPath = Paths.get("./data/chatterBox.txt");
        if (!Files.exists(txtPath)) {
            try {
                Files.createFile(txtPath);
                System.out.println("File created: " + txtPath.getFileName());
            } catch (Exception e) {
                System.out.println("Error creating file:");
                e.printStackTrace();
            }
        } else {
            try {
                List<String> lines = Files.readAllLines(txtPath);
                for (String line : lines) {
                    String[] parts = line.split(" \\| ");
                    String description = parts[2];

                    if (line.startsWith("T |")) {
                        String task = description;
                        ToDos newToDo = new ToDos(task);
                        tasks.add(newToDo);
                    } else if (line.startsWith("D |")) {
                        Deadline newDeadline = new Deadline(description, LocalDate.parse(parts[3]));
                        tasks.add(newDeadline);
                    } else if (line.startsWith("E |")) {
                        Events newEvent = new Events(description, LocalDateTime.parse(parts[3]),
                                LocalDateTime.parse(parts[4]));
                        tasks.add(newEvent);
                    }
                }
            } catch (Exception e) {
                System.out.println("Error reading file:");
                e.printStackTrace();
            }

        }

        System.out.println("        Hello! I'm " + botName);
        System.out.println("        What can I do for you?");

        while (isChatting) {
            try {
                if (scanner.hasNextLine()) {
                    String userInput = scanner.nextLine();
                    if (userInput.equalsIgnoreCase("bye")) {
                        isChatting = false;
                        break;

                    } else if (userInput.equalsIgnoreCase("list")) {
                        for (int i = 0; i < tasks.size(); i++) {
                            System.out.println("        " + (i + 1) + "." + tasks.get(i));
                        }

                    } else if (userInput.startsWith("mark")) {
                        String[] parts = userInput.split(" ");
                        int taskNumber = Integer.parseInt(parts[1]) - 1;// generated by github copilot to get the
                                                                        // taskNumber
                        Task index = tasks.get(taskNumber);
                        index.markAsDone();
                        saveTasks(txtPath, tasks);

                        System.out.println("        Nice! I've marked this task as done:");
                        System.out.println("          " + tasks.get(taskNumber).toString());

                    } else if (userInput.startsWith("unmark")) {
                        String[] parts = userInput.split(" ");
                        int taskNumber = Integer.parseInt(parts[1]) - 1; // generated by github copilot to get the
                                                                         // taskNumber
                        Task index = tasks.get(taskNumber);
                        index.markAsNotDone();
                        saveTasks(txtPath, tasks);
                        System.out.println("        OK, I've marked this task as not done yet:");
                        System.out.println("          " + tasks.get(taskNumber).toString());

                    } else if (userInput.startsWith("delete")) {
                        String[] parts = userInput.split(" ");
                        int taskNumber = Integer.parseInt(parts[1]) - 1;
                        if (userInput.length() <= 6 || userInput.substring(7).trim().isEmpty()) {
                            throw new ChatterBoxException("     OOPS!!! The delete cannot be empty.");
                        }
                        Task removedTask = tasks.remove(taskNumber);
                        saveTasks(txtPath, tasks);

                        System.out.println("        Noted. I've removed this task:");
                        System.out.println("          " + removedTask.toString());
                        System.out.println("        Now you have " + tasks.size() + " tasks in the list.");

                    } else if (userInput.startsWith("todo")) {
                        String task = userInput.substring(userInput.indexOf(" ") + 1); // generated by github copilot to
                                                                                       // get
                                                                                       // the
                                                                                       // task description
                        if (userInput.length() <= 4 || userInput.substring(5).trim().isEmpty()) { // generated by github
                                                                                                  // copilot to
                                                                                                  // check if
                                                                                                  // the
                                                                                                  // description
                                                                                                  // is empty
                            throw new ChatterBoxException("     OOPS!!! The description of a todo cannot be empty.");
                        }
                        ToDos newToDo = new ToDos(task);
                        tasks.add(newToDo);
                        saveTasks(txtPath, tasks);

                        System.out.println("        Got it. I've added this task:");
                        System.out.println("          " + newToDo.toString());
                        System.out.println("        Now you have " + tasks.size() + " tasks in the list.");
                    } else if (userInput.startsWith("deadline")) {
                        if (userInput.length() <= 8 || userInput.substring(9).trim().isEmpty()) {
                            throw new ChatterBoxException(
                                    "     OOPS!!! The description of a deadline cannot be empty.");
                        }
                        String[] parts = userInput.split("/by", 2);
                        String firstPart = parts[0].trim();
                        String task = firstPart.substring(firstPart.indexOf(" ") + 1);
                        LocalDate deadline = LocalDate.parse(parts[1].trim());

                        Deadline newDeadline = new Deadline(task, deadline);
                        tasks.add(newDeadline);
                        saveTasks(txtPath, tasks);

                        System.out.println("        Got it. I've added this task:");
                        System.out.println("          " + newDeadline.toString());
                        System.out.println("        Now you have " + tasks.size() + " tasks in the list.");
                    } else if (userInput.startsWith("event")) {
                        if (userInput.length() <= 5 || userInput.substring(6).trim().isEmpty()) {
                            throw new ChatterBoxException("     OOPS!!! The description of an event cannot be empty.");
                        }
                        String[] parts = userInput.split("/to", 2); // generated by github copilot to get the task
                                                                    // description
                        String firstPart = parts[0].trim(); // generated by github copilot to get the task description
                        String taskAndAt = firstPart.substring(firstPart.indexOf(" ") + 1); // generated by github
                                                                                            // copilot
                                                                                            // to
                                                                                            // get the task description
                        String[] taskParts = taskAndAt.split("/from", 4); // generated by github copilot to get the task
                                                                          // description
                        String task = taskParts[0].trim(); // generated by github copilot to get the task description
                        LocalDateTime at = LocalDateTime.parse(taskParts[1].trim()); // generated by github copilot to
                                                                                     // get the task description
                        LocalDateTime to = LocalDateTime.parse(parts[1].trim()); // generated by github copilot to get
                                                                                 // the task description

                        Events newEvent = new Events(task, at, to);
                        tasks.add(newEvent);
                        saveTasks(txtPath, tasks);

                        System.out.println("        Got it. I've added this task:");
                        System.out.println("          " + newEvent.toString());
                        System.out.println("        Now you have " + tasks.size() + " tasks in the list.");
                    }

                    else {
                        Task newTask = new Task(userInput);
                        tasks.add(newTask);
                        System.out.println("        added: " + userInput);
                    }
                } else {
                    isChatting = false;
                }
            } catch (ChatterBoxException e) {
                System.out.println(e.getMessage());
            }
        }
        System.out.println("        Bye. Hope to see you again soon!");
        scanner.close();
    }
}
