package chatterbox.parser;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;

import chatterbox.exception.ChatterBoxException;
import chatterbox.storage.Storage;
import chatterbox.task.Deadline;
import chatterbox.task.Events;
import chatterbox.task.Task;
import chatterbox.task.TaskList;
import chatterbox.task.ToDos;
import chatterbox.ui.Ui;

public class Parser {
    /**
     * Parses the user input and run the command.
     * commands include adding tasks (todo, deadline, event), listing, marking,
     * unmarking, and deleting tasks.
     *
     * @param userInput The string user input
     * @param tasks     An ArrayList containing current tasks.
     * @param ui        The UI object to interact with the user.
     * @param storage   The Storage object to save chat to data file.
     * @throws ChatterBoxException If the command is invalid
     */
    public static void parse(String userInput, TaskList tasks, Ui ui, Storage storage) throws ChatterBoxException {
        if (userInput.equalsIgnoreCase("bye")) {
            ui.showBye();
        } else if (userInput.equalsIgnoreCase("list")) {
            for (int i = 0; i < tasks.getSize(); i++) {
                ui.showMessage((i + 1) + "." + tasks.getTasks(i));
            }

        } else if (userInput.startsWith("mark")) {
            String[] parts = userInput.split(" ");
            int taskNumber = Integer.parseInt(parts[1]) - 1;// generated by github copilot to get the
                                                            // taskNumber
            Task index = tasks.getTasks(taskNumber);
            index.markAsDone();

            storage.saveTasks(tasks.getTasks());

            ui.showMessage("Nice! I've marked this task as done: ");
            ui.showMessage(tasks.getTasks(taskNumber).toString());

        } else if (userInput.startsWith("unmark")) {
            String[] parts = userInput.split(" ");
            int taskNumber = Integer.parseInt(parts[1]) - 1; // generated by github copilot to get the
                                                             // taskNumber
            Task index = tasks.getTasks(taskNumber);
            index.markAsNotDone();
            storage.saveTasks(tasks.getTasks());
            ui.showMessage("OK, I've marked this task as not done yet:");
            ui.showMessage(tasks.getTasks(taskNumber).toString());

        } else if (userInput.startsWith("delete")) {
            String[] parts = userInput.split(" ");
            int taskNumber = Integer.parseInt(parts[1]) - 1;
            if (userInput.length() <= 6 || userInput.substring(7).trim().isEmpty()) {
                throw new ChatterBoxException("     OOPS!!! The delete cannot be empty.");
            }
            ui.showMessage("Noted. I've removed this task:");
            ui.showMessage(tasks.getTasks(taskNumber).toString());
            ui.showMessage("Now you have " + tasks.getSize() + " tasks in the list.");
            tasks.removeTask(taskNumber);
            storage.saveTasks(tasks.getTasks());

        } else if (userInput.startsWith("find")) {
            String[] parts = userInput.split(" ");
            ArrayList<Task> foundTasks = new ArrayList<Task>();
            for (int i = 0; i < tasks.getSize();i++) {
                Task currentTask = tasks.getTasks(i);
                if (currentTask.toString().contains(parts[1].trim())) {
                    foundTasks.add(currentTask);
                }
            }
            ui.showMessage("Here are the mathcing task in your list:");
            for (int i = 0; i < foundTasks.size(); i++) {
                ui.showMessage((i + 1) + "." + foundTasks.get(i));
            }

        } else if (userInput.startsWith("todo")) {
            String task = userInput.substring(userInput.indexOf(" ") + 1); // generated by github copilot to
                                                                           // get
                                                                           // the
                                                                           // task description
            if (userInput.length() <= 4 || userInput.substring(5).trim().isEmpty()) { // generated by github
                                                                                      // copilot to
                                                                                      // check if
                                                                                      // the
                                                                                      // description
                                                                                      // is empty
                throw new ChatterBoxException("     OOPS!!! The description of a todo cannot be empty.");
            }
            ToDos newToDo = new ToDos(task);
            tasks.addTask(newToDo);
            storage.saveTasks(tasks.getTasks());

            ui.showMessage("Got it. I've added this task:");
            ui.showMessage(newToDo.toString());
            ui.showMessage("Now you have " + tasks.getSize() + " tasks in the list.");
        } else if (userInput.startsWith("deadline")) {
            if (userInput.length() <= 8 || userInput.substring(9).trim().isEmpty()) {
                throw new ChatterBoxException(
                        "     OOPS!!! The description of a deadline cannot be empty.");
            }
            String[] parts = userInput.split("/by", 2);
            String firstPart = parts[0].trim();
            String task = firstPart.substring(firstPart.indexOf(" ") + 1);
            LocalDate deadline = LocalDate.parse(parts[1].trim());

            Deadline newDeadline = new Deadline(task, deadline);
            tasks.addTask(newDeadline);
            storage.saveTasks(tasks.getTasks());

            ui.showMessage("Got it. I've added this task:");
            ui.showMessage(newDeadline.toString());
            ui.showMessage("Now you have " + tasks.getSize() + " tasks in the list.");
        } else if (userInput.startsWith("event")) {
            if (userInput.length() <= 5 || userInput.substring(6).trim().isEmpty()) {
                throw new ChatterBoxException("     OOPS!!! The description of an event cannot be empty.");
            }
            String[] parts = userInput.split("/to", 2); // generated by github copilot to get the task
                                                        // description
            String firstPart = parts[0].trim(); // generated by github copilot to get the task description
            String taskAndAt = firstPart.substring(firstPart.indexOf(" ") + 1); // generated by github
                                                                                // copilot
                                                                                // to
                                                                                // get the task description
            String[] taskParts = taskAndAt.split("/from", 4); // generated by github copilot to get the task
                                                              // description
            String task = taskParts[0].trim(); // generated by github copilot to get the task description
            LocalDateTime at = LocalDateTime.parse(taskParts[1].trim()); // generated by github copilot to
                                                                         // get the task description
            LocalDateTime to = LocalDateTime.parse(parts[1].trim()); // generated by github copilot to get
                                                                     // the task description

            Events newEvent = new Events(task, at, to);
            tasks.addTask(newEvent);
            storage.saveTasks(tasks.getTasks());

            ui.showMessage("Got it. I've added this task:");
            ui.showMessage(newEvent.toString());
            ui.showMessage("Now you have " + tasks.getSize() + " tasks in the list.");
        }

        else {
            Task newTask = new Task(userInput);
            tasks.addTask(newTask);
            ui.showMessage("added: " + userInput);
        }
    }
}
