package chatterbox.parser;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;

import chatterbox.exception.ChatterBoxException;
import chatterbox.storage.Storage;
import chatterbox.task.Deadline;
import chatterbox.task.Events;
import chatterbox.task.Task;
import chatterbox.task.TaskList;
import chatterbox.task.ToDos;
import chatterbox.ui.Ui;

/**
 * Deals with making sense of the user command.
 * It parses the raw user input and executes the corresponding logic by
 * interacting with the TaskList, Ui, and Storage components.
 */
public class Parser {
    /**
     * Parses the user input and run the command.
     * commands include adding tasks (todo, deadline, event), listing, marking,
     * unmarking, and deleting tasks.
     *
     * @param userInput The string user input
     * @param tasks     An ArrayList containing current tasks.
     * @param ui        The UI object to interact with the user.
     * @param storage   The Storage object to save chat to data file.
     * @throws ChatterBoxException If the command is invalid
     */
    public static String parse(String userInput, TaskList tasks, Ui ui, Storage storage) throws ChatterBoxException {
        assert tasks != null : "Tasklist shouln't be null";
        assert ui != null : "Ui shouln't be null";
        assert storage != null : "Storage shouln't be null";

        String userinput = userInput.split(" ")[0].toLowerCase();

        switch (userinput) {
            case "bye":
                return ui.showBye();
            case "list":
                return handleList(tasks, ui);
            case "mark":
                return handleMark(userInput, tasks, storage);
            case "unmark":
                return handleUnmark(userInput, tasks, storage);
            case "delete":
                return handleDelete(userInput, tasks, storage);
            case "tag":
                return handleTag(userInput, tasks, storage);
            case "todo":
                return handleTodo(userInput, tasks, storage, ui);
            case "deadline":
                return handleDeadline(userInput, tasks, storage, ui);
            case "event":
                return handleEvent(userInput, tasks, storage, ui);
            case "find":
                return handleFind(userInput, tasks, ui);
            default:
                throw new ChatterBoxException("     OOPS!!! I'm sorry, but I don't know what that means :-(");
        }
    }

    /**
     * Formats and returns the list of all tasks currently in the TaskList.
     *
     * @param tasks The TaskList to retrieve tasks from.
     * @param ui    The UI object for formatting messages.
     * @return A formatted string of all tasks.
     */
    private static String handleList(TaskList tasks, Ui ui) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < tasks.getSize(); i++) {
            sb.append(ui.showMessage((i + 1) + "." + tasks.getTasks(i)));
        }
        return sb.toString();
    }

    /**
     * Marks a specific task as done based on the index provided in user input.
     *
     * @param userInput The full command string containing the task index.
     * @param tasks     The TaskList to update.
     * @param storage   The Storage to save the updated list.
     * @return A confirmation message.
     */
    private static String handleMark(String userInput, TaskList tasks, Storage storage) {
        String[] parts = userInput.split(" ");
        int taskNumber = Integer.parseInt(parts[1]) - 1;// generated by github copilot to get the
                                                        // taskNumber
        Task index = tasks.getTasks(taskNumber);
        index.markAsDone();

        storage.saveTasks(tasks.getTasks());

        return "Nice! I've marked this task as done: \n" + tasks.getTasks(taskNumber).toString();
    }

    /**
     * Marks a specific task as not done based on the index provided in user input.
     *
     * @param userInput The full command string containing the task index.
     * @param tasks     The TaskList to update.
     * @param storage   The Storage to save the updated list.
     * @return A confirmation message.
     */
    private static String handleUnmark(String userInput, TaskList tasks, Storage storage) {
        String[] parts = userInput.split(" ");
        int taskNumber = Integer.parseInt(parts[1]) - 1; // generated by github copilot to get the
                                                         // taskNumber
        Task index = tasks.getTasks(taskNumber);
        index.markAsNotDone();
        storage.saveTasks(tasks.getTasks());

        return "OK, I've marked this task as not done yet: \n" + tasks.getTasks(taskNumber).toString();
    }

    /**
     * Deletes a task from the list based on the provided index.
     *
     * @param userInput The command string containing the index to delete.
     * @param tasks     The list to remove the task from.
     * @param storage   The storage to update after deletion.
     * @return A message confirming the removal and the new list size.
     * @throws ChatterBoxException If the index is empty.
     */
    private static String handleDelete(String userInput, TaskList tasks, Storage storage) throws ChatterBoxException {
        String[] parts = userInput.split(" ");
        int taskNumber = Integer.parseInt(parts[1]) - 1;
        if (userInput.length() <= 6 || userInput.substring(7).trim().isEmpty()) {
            throw new ChatterBoxException("     OOPS!!! The delete cannot be empty.");
        }
        tasks.removeTask(taskNumber);
        storage.saveTasks(tasks.getTasks());
        return "Noted. I've removed this task: \n" + tasks.getTasks(taskNumber + 1).toString() +
                "Now you have \n" + tasks.getSize() + " tasks in the list.";
    }

    /**
     * Finds tasks that contain the keyword specified in user input.
     *
     * @param userInput The command string containing the search keyword.
     * @param tasks     The TaskList to search within.
     * @param ui        The UI object to format results.
     * @return A list of matching tasks.
     */
    private static String handleFind(String userInput, TaskList tasks, Ui ui) {
        StringBuilder sb = new StringBuilder();
        String[] parts = userInput.split(" ");
        ArrayList<Task> foundTasks = new ArrayList<Task>();
        for (int i = 0; i < tasks.getSize(); i++) {
            Task currentTask = tasks.getTasks(i);
            if (currentTask.toString().contains(parts[1].trim())) {
                foundTasks.add(currentTask);
            }
        }
        sb.append(ui.showMessage("Here are the matching task in your list: \n"));
        for (int i = 0; i < foundTasks.size(); i++) {
            sb.append(ui.showMessage((i + 1) + "." + foundTasks.get(i)));
        }
        return sb.toString();
    }

    /**
     * Adds a custom tag to a task.
     *
     * @param userInput The command string containing the index and the tag.
     * @param tasks     The TaskList to update.
     * @param storage   The storage to save changes.
     * @return A confirmation message.
     */
    private static String handleTag(String userInput, TaskList tasks, Storage storage) {
        String[] parts = userInput.split(" ");
        int taskNumber = Integer.parseInt(parts[1]) - 1;
        String tag = parts[2];
        tasks.addTag(taskNumber, tag);
        storage.saveTasks(tasks.getTasks());

        return "This task has been tagged: \n" + tasks.getTasks(taskNumber).toString();
    }

    /**
     * Handles the creation and addition of a ToDo task.
     *
     * @throws ChatterBoxException If the description is empty.
     */
    private static String handleTodo(String userInput, TaskList tasks, Storage storage, Ui ui)
            throws ChatterBoxException {
        String task = userInput.substring(userInput.indexOf(" ") + 1); // generated by github copilot to
                                                                       // get
                                                                       // the
                                                                       // task description
        if (userInput.length() <= 4 || userInput.substring(5).trim().isEmpty()) { // generated by github
                                                                                  // copilot to
                                                                                  // check if
                                                                                  // the
                                                                                  // description
                                                                                  // is empty
            throw new ChatterBoxException("     OOPS!!! The description of a todo cannot be empty.");
        }
        ToDos newToDo = new ToDos(task);
        tasks.addTask(newToDo);
        storage.saveTasks(tasks.getTasks());
        StringBuilder sb = new StringBuilder();
        sb.append(ui.showMessage("Got it. I've added this task:"));
        sb.append(ui.showMessage(newToDo.toString()));
        sb.append(ui.showMessage("Now you have " + tasks.getSize() + " tasks in the list."));
        return sb.toString();
    }

    /**
     * Handles the creation and addition of a Deadline task.
     *
     * @throws ChatterBoxException If description is empty or format is wrong.
     */
    private static String handleDeadline(String userInput, TaskList tasks, Storage storage, Ui ui)
            throws ChatterBoxException {
        if (userInput.length() <= 8 || userInput.substring(9).trim().isEmpty()) {
            throw new ChatterBoxException(
                    "     OOPS!!! The description of a deadline cannot be empty.");
        }
        StringBuilder sb = new StringBuilder();
        String[] parts = userInput.split("/by", 2);
        String firstPart = parts[0].trim();
        String task = firstPart.substring(firstPart.indexOf(" ") + 1);
        LocalDate deadline = LocalDate.parse(parts[1].trim());

        Deadline newDeadline = new Deadline(task, deadline);
        tasks.addTask(newDeadline);
        storage.saveTasks(tasks.getTasks());
        sb.append(ui.showMessage("Got it. I've added this task:"));
        sb.append(ui.showMessage(newDeadline.toString()));
        sb.append(ui.showMessage("Now you have " + tasks.getSize() + " tasks in the list."));
        return sb.toString();
    }

    /**
     * Handles the creation and addition of an Event task.
     *
     * @throws ChatterBoxException If formatting or dates are invalid.
     */
    private static String handleEvent(String userInput, TaskList tasks, Storage storage, Ui ui)
            throws ChatterBoxException {
        if (userInput.length() <= 5 || userInput.substring(6).trim().isEmpty()) {
            throw new ChatterBoxException("     OOPS!!! The description of an event cannot be empty.");
        }
        StringBuilder sb = new StringBuilder();
        String[] parts = userInput.split("/to", 2); // generated by github copilot to get the task
                                                    // description
        String firstPart = parts[0].trim(); // generated by github copilot to get the task description
        String taskAndAt = firstPart.substring(firstPart.indexOf(" ") + 1); // generated by github
                                                                            // copilot
                                                                            // to
                                                                            // get the task description
        String[] taskParts = taskAndAt.split("/from", 4); // generated by github copilot to get the task
                                                          // description
        String task = taskParts[0].trim(); // generated by github copilot to get the task description
        try {
            LocalDateTime at = LocalDateTime.parse(taskParts[1].trim()); // generated by github copilot to
                                                                         // get the task description
            LocalDateTime to = LocalDateTime.parse(parts[1].trim()); // generated by github copilot to get
                                                                     // the task description

            Events newEvent = new Events(task, at, to);
            tasks.addTask(newEvent);
            storage.saveTasks(tasks.getTasks());

            sb.append(ui.showMessage("Got it. I've added this task:"));
            sb.append(ui.showMessage(newEvent.toString()));
            sb.append(ui.showMessage("Now you have " + tasks.getSize() + " tasks in the list."));
            return sb.toString();
        } catch (java.time.format.DateTimeParseException e) {
            throw new ChatterBoxException("     OOPS!!! he event date format is invalid. Please use YYYY-MM-DDTHH:MM.");
        }
    }
}
